<?php echo $this->doctype(); ?>

<html lang="vi">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="fusioncharts/js/fusioncharts.js"></script>
        <script type="text/javascript" src="fusioncharts/js/themes/fusioncharts.theme.ocean.js"></script>
         
    </head>
    <body>
  <!--      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">&nbsp;<?php echo $this->translate('Trang chủ trung tâm ngoại ngữ') ?></a>
                </div>
    <!--            <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('blog') ?>"><?php echo $this->translate('Đăng nhập') ?></a></li>
                    </ul>
                     <ul class="nav navbar-nav">
                        <li class="active"><a href="http://luanvan.local/">Luận văn</a></li>
                    </ul>
                </div>
                
                <!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2016 - <?php echo date('Y') ?> by MrT Group -  <?php echo $this->translate('All rights reserved.') ?></p>
                 <p>Website made by MrT - Copyright Green House Group <a href="http://ctu.edu.vn/" title="linktoweb">www.ctu.edu.vn</a></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
