<section class="login-confirm">
<h2>Đăng nhập thành công</h2>
<p> Welcome! <?php echo $this->user_email; ?> </p>

<p><a href="http://localhost/menu">Danh mục chức năng</a></p>
<p><a href="http://localhost/users/login">Quay lại trang đăng nhập</a></p>
<p><a href="http://localhost/users/register">Quay lại trang đăng ký</a></p>
<p><a href="http://localhost/users/register/user">Xem danh sách người dùng</a></p>
</section>
