<section class="login">
<h2>Đăng nhập</h2>
<?php if($this->error): ?>
<p class="error">
    Đã có sự cố với đăng nhập của bạn. Vui lòng đọc chỉ dẫn và làm theo!
</p>
<?php endif ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL, array('controller'=>'Login', 'action'=>'process')));
$form->setAttribute('method','post');
echo $this->form()->openTag($form);
?>
<dl class="zend_form">

<dt><?php echo $this->formLabel($form->get('email')); ?></dt>
<dd><?php
    echo $this->formElement($form->get('email'));
    echo $this->formElementErrors($form->get('email'));
?></dd>
<dt><?php echo $this->formLabel($form->get('password')); ?></dt>
<dd><?php
    echo $this->formElement($form->get('password'));
    echo $this->formElementErrors($form->get('password'));
?></dd>

<dd><br> <input type ="submit" value="Submit"></dd>
</dl>
<?php echo $this->form()->closeTag() ?>
</section>