<?php

$title = 'Đây là giao diện menu chọn các chức năng của hệ thống';
$this->headTitle($title);
?>
<!DOCTYPE html>
<html>
<head>
	<title>Các chương trình học</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <style>
        body {
        background: #ffffff url("img/img.jpg") no-repeat;
        }
        .jumbotron { 
        background-color: #3399CC; /* Orange */
        color: #ffffff;
        heith: 200px;
        #tb1 {
        padding: 10px;
        border: 0px solid;
        margin: 20px;
        width:900px ;
        }
        #panel1{
            max-width: 60%; display: block;
        }
            
       #panel2{
            max-width: 40%; display: block;
             max-height: 50%; display: block;
        }
            
       #panel2{
             max-width: 40%; display: block;
             max-height: 50%; display: block;
        }
      <!--  #panel1 {width: 1000px;}  -->
      </style>
</head>
<body>
<div class="container text-center">
   <h3> <a href="http://mrt.local"><button type="button" class="btn btn-info">
          <span class="glyphicon glyphicon-home"></span> Trang chủ
            </button></a> <br>
            Các chương trình đào tạo của trung tâm
        </h3> <hr>  
<img src="http://luanvan.local/img/chuongtrinhhoc/ct1.jpg" width=95%>
<img src="http://luanvan.local/img/chuongtrinhhoc/ct2.jpg" width=95%>
<img src="http://luanvan.local/img/chuongtrinhhoc/ct3.jpg" width=95%>
<img src="http://luanvan.local/img/chuongtrinhhoc/ct4.jpg" width=95%>
<img src="http://luanvan.local/img/chuongtrinhhoc/ct5.jpg" width=95%>
</div>
</body>


