<?php

$title = 'Đây là giao diện menu chọn các chức năng của hệ thống';
$this->headTitle($title);

?>
<body>

   
  
<div class="container" id="menu">
    <div>
        <div class="jumbotron text-center">
             <h1>Foreign Languages Center</h1> 
 <!-- <p>Chúng tôi là chuyên gia trong lĩnh vực sữa tươi và các sản phẩm về sữa</p> -->
            <p>Uy tín - Chất lượng - Vững bền</p> 
                <a href="http://ctu.edu.vn" target="_blank"><button type="button" class="btn btn-danger">Trang chủ</button>  </a>           
        </div> 
    </div>
</div> 

<div class="container" id="content"><p>Chào giảng viên <?php echo $id; ?></p>
    <h1>Danh mục chức năng dành cho giảng viên</h1>
    <ol>
        <li>Xem kết quả đánh giá của học viên</li>
        <li>Nhập điểm</li>
        <li>Xem thông tin cá nhân</li>
    </ol>
    
</div>
      
</body>


