<?php

$title = 'Đây là giao diện menu chọn các chức năng của hệ thống';
$this->headTitle($title);
?>
<!DOCTYPE html>
<html>
<head>
	<title>Các ngôn ngữ</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <style>
        body {
        background: #ffffff url("img/img.jpg") no-repeat;
        }
        .jumbotron { 
        background-color: #3399CC; /* Orange */
        color: #ffffff;
        heith: 200px;
        #tb1 {
        padding: 10px;
        border: 0px solid;
        margin: 20px;
        width:900px ;
        }
        #panel1{
            max-width: 60%; display: block;
        }
            
       #panel2{
            max-width: 40%; display: block;
             max-height: 50%; display: block;
        }
            
       #panel2{
             max-width: 40%; display: block;
             max-height: 50%; display: block;
        }
      <!--  #panel1 {width: 1000px;}  -->
      </style>
</head>
<body>
    <div id="dsngonngu" class="container text-center">
        
        <h3> <a href="http://mrt.local"><button type="button" class="btn btn-info">
          <span class="glyphicon glyphicon-home"></span> Trang chủ
            </button></a> <br>
            Danh sách các ngôn ngữ Trung Tâm có đào tạo
        </h3> <hr>
<?php
    //require_once('../../conn.php');
$conn=mysql_connect("localhost", "root", "") or die("can't connect database");
mysql_select_db("mrt",$conn); 
mysql_query("set names 'utf8'",$conn);
$ngonngu = mysql_query('select * from ngonngu') or die("Không thể tìm ngôn ngữ");
if(mysql_num_rows($ngonngu)>0){
    echo ' <table class="table table-bordered  text-center">
    <thead class="text-center">
      <tr>
        <th>Mã ngôn ngữ</th>
        <th>Tên ngôn ngữ</th>
        <th>Mô tả ngôn ngữ</th>
      </tr>
    </thead><tbody>';
    while($row = mysql_fetch_array($ngonngu)){
        echo '<tr>';
        echo "<td>".$row["mann"]." </td><td> " . $row["tennn"]." </td><td> ". $row["mota"] . "</td>";
        echo '</tr>';
    }
    echo '</tbody></table>';
    
} else echo "Không có ngôn ngữ trong csdl!";
?>
    </div>
</body>


