<?php

$title = 'Them nhan vien';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('nhanvien', array('action'=>'index'));?>">Xem danh sach nhan vien</a>
</p>

<table class="table">
<tr>
    <th>ID</th>
    <th>Blog</th>
    <th>Created</th>
    <th> </th>
</tr>
<?php foreach ($blogs as $blog) : ?>
<tr>
    <td><?php echo $this->escapeHtml($blog->id);?></td>
    <td><?php echo $this->escapeHtml($blog->blog);?></td>
    <td><?php echo $this->escapeHtml($blog->created);?></td>
    <td>
        <a href="<?php echo $this->url('blog',
            array('action'=>'update', 'id' => $blog->id));?>">Update</a>
        <a href="<?php echo $this->url('blog',
            array('action'=>'delete', 'id' => $blog->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>